export default function Reports() {
    return (
        <div className="p-8 space-y-6">
            <h1 className="text-h2 font-display uppercase">AI Generated Reports</h1>
            <p className="text-text-muted font-ui text-body">
                View detailed summaries and historical analyses of your cloud infrastructure.
            </p>
            <div className="space-y-4">
                {[1, 2, 3].map((i) => (
                    <div key={i} className="bg-surface border border-border p-6 hover:border-text-primary cursor-pointer transition-colors flex justify-between items-center group">
                        <div>
                            <h3 className="text-body font-bold text-text-primary group-hover:text-accent-red transition-colors">Weekly Cost Summary - W{i}</h3>
                            <p className="text-micro text-text-muted mt-1">Generated by Reporting Agent</p>
                        </div>
                        <div className="text-micro font-bold tracking-widest text-text-secondary">
                            PDF / CSV
                        </div>
                    </div>
                ))}
            </div>
        </div>
    );
}
